### ISSUE TITLE
Allow container inheritence

### ISSUE THREAD

**Issue by pysyun** [pysyun/docker-tor-runtime-golang#12]
Currently, we cannot inherit from this container:
https://github.com/pysyun/docker-tor-runtime-golang/blob/master/Dockerfile#L24

After we specify a new ENTRYPOINT, our commands for the current ENTRYPOINT will not be executed any more.

**Comment by pysyun** [comment]
Still, we need to start TOR somehow. 
So:
1. Let's create a file ./tor.sh.
2. Let's create a file ./start.sh.
3. Let's specify start.sh as the entry point.
4. The first thing start.sh calls must be tor.sh.
5. After inheriting a container, we will override only start.sh.
6. But will also call tor.sh.

**Comment by ChoNakyun** [comment]
We solved it.
