### ISSUE TITLE
Remove listening to global IP interface

### ISSUE THREAD

**Issue by pysyun** [pysyun/docker-tor-runtime-golang#4]
This is not needed:
https://github.com/pysyun/docker-tor-runtime-golang/blob/master/Dockerfile#L8-L11
The IP adress 0.0.0.0 means "all network cards". It makes the service listen for connection from all IP interfaces.
This produces a security hole when someone can access the server.
And also, we do not need to EXPOSE the port. By the same reason.

**Comment by ChoNakyun** [comment]
Fixed it.
