### ISSUE TITLE
Isn't the TOR service started automatically in background?

### ISSUE THREAD

**Issue by pysyun** [pysyun/docker-tor-runtime-golang#5]
When this command is replaced in the child container, TOR will not be started any more.
But, we can expect that TOR is automatically started in background as a services. At least, it always works like that.

**Comment by ChoNakyun** [comment]
Fixed it.

**Comment by pysyun** [comment]
Are we sure that TOR is not started automatically (as a service) after it is installed?
https://github.com/pysyun/docker-tor-runtime-golang/blob/master/Dockerfile#L19
