### ISSUE TITLE
Move code to "go_http_worker"

### ISSUE THREAD

**Issue by pysyun** [pysyun/docker-tor-runtime-golang#7]
The "docker-tor-runtime-golang" project should contain a base container for all TOR micro-services.
While the "go_http_worker" project should contain specifically the HTTP worker which is based on the TOR container.
I will later create a Docker Hub for "docker-tor-runtime-golang" and you will be able to inherit the "docker-tor-runtime-golang" container.
For now, you can just copy the Dockerfile. This will be good enough.

**Comment by ChoNakyun** [comment]
Fixed it.

**Comment by pysyun** [comment]
- Also the new repository must have the appropriate Dockerfile as well.

**Comment by ChoNakyun** [comment]
I did it.
